spring:
  application:
    name: book-my-show
  datasource:
    url: jdbc:postgresql://bms-database:5432/bms_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes in milliseconds
  data:
    redis:
      host: redis-cache
      port: 6379
      ssl:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect